---
- hosts: all
  vars_files:
    - vars.yml
    - system_requirements.yml
  gather_facts: false
  become: yes

  tasks:

  - name: Create superuser.
    user: >
      name={{ lookup('file', 'credentials/' + nickname + '/super_user_name') }}
      password={{ lookup('file', 'credentials/' + nickname + '/super_user_password_crypted') }} state=present
      groups=sudo
      shell=/bin/bash

  - name: Superuser bash_profile file update.
    template: >
      src=configurations/bash_profile_superuser.j2
      dest=/home/{{ lookup('file', 'credentials/' + nickname + '/super_user_name') }}/.profile
      backup=yes
      owner={{ lookup('file', 'credentials/' + nickname + '/super_user_name') }}
      group={{ lookup('file', 'credentials/' + nickname + '/super_user_name') }}
      mode=0644

  - name: Add authorized key.
    authorized_key: >
      user={{ lookup('file', 'credentials/' + nickname + '/super_user_name') }}
      key={{ lookup('file', '~/.ssh/id_rsa.pub') }}

  - name: SSH configuration file update.
    template: >
      src=configurations/sshd_config.j2
      dest=/etc/ssh/sshd_config
      backup=yes 
      owner=0 
      group=0 
      mode=0644
    notify: restart ssh

  - name: Set localtime to {{ timezone }}
    shell: "/bin/cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime"

  - name: Set timezone to {{ timezone }}
    template: src=configurations/timezone.j2 dest=/etc/timezone
    notify: update tzdata

  handlers:
    - name: update tzdata
      shell: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

    - name: restart ssh
      become: yes
      action: service name=ssh state=restarted enabled=yes
